CROSS =
CC = gcc
ODIR = .build

CFLAGS = -Wall \
		 -Werror

EXTRAINCDIRS += ../../bitree

CFLAGS += $(patsubst %,-I %,$(EXTRAINCDIRS))
CFLAGS += -MD -MP -MF .dep/$(@F).d

LFLAGS =

bitree-obj = bitree/bitree.o

main-obj += $(bitree-obj)
main-obj += main.o

OUT += main

all: $(OUT)

main: $(addprefix $(ODIR)/,$(main-obj))
	$(CROSS)$(CC) $(CFLAGS) -o $@ $^

$(ODIR)/$(bitree-obj): ../../bitree/bitree.c
	@mkdir -p $(@D)
	@echo ">>> $<"
	$(CROSS)$(CC) $(CFLAGS) -c $< -o $@

$(ODIR)/%.o: %.c
	@mkdir -p $(@D)
	@echo ">>> $<"
	$(CROSS)$(CC) $(CFLAGS) -c $< -o $@

include $(shell mkdir .dep 2>/dev/null) $(wildcard .dep/*)

clean:
	$(RM) -r $(ODIR) .dep
	$(RM) $(OUT)

.PHONY: all clean
