/* Define the initialize function prototype */
typedef void (*init_fn_t)(void);

/*
 * This macro is to define an function pointer which pointed the specific init function
 * and located in the customize section in order to call initialize function
 * together from main.
 */
#define DECLARE_INIT(func)         \
	static init_fn_t __fn_ ## func \
	__attribute__((unused, section("init_sec"))) = func

/* These two symbols are generated by ld (gcc linker). */
extern init_fn_t __start_init_sec;
extern init_fn_t __stop_init_sec;
